### ISSUE TITLE
Licensing to BSD 2-clause

### ISSUE THREAD

**Issue by jburel** [IDR/idr-notebooks#110]
Given the funding, the provenance and the academic nature of the work, there is no rationale for having these work under the GPL-2 license and the IDR team has discussed relicensing it under the permissive BSD 2-clause license.
This will also align this repository with repositories with similar content e.g. guides

The proposal is to 
* Change the license section on the notebook
* Add a license file

Contributions to this repository have been mainly done by current members of the OME team or previous members of the team while working for the University.
@ac744 would you be willing to relicense your contributions under the more permissive BSD-2 clause?

**Comment by sbesson** [comment]
I authorize my contributions to the IDR notebooks to be relicensed as BSD-2.

**Comment by jburel** [comment]
cc @jburel @joshmoore @manics @olatarkowska @dominikl @bramalingam @eleanorwilliams @hflynn

**Comment by eleanorwilliams** [comment]
I authorize my contributions to the IDR notebooks to be relicensed as BSD-2.

**Comment by dominikl** [comment]
I authorize my contributions to the IDR notebooks to be relicensed as BSD-2.

**Comment by manics** [comment]
I authorize my contributions to the IDR notebooks to be relicensed as BSD-2.

**Comment by joshmoore** [comment]
I authorize my contributions to the IDR notebooks to be relicensed as BSD-2.

**Comment by ac744** [comment]
I authorize my contributions to the IDR notebooks to be relicensed as BSD-2

**Comment by jburel** [comment]
Thanks @ac744

**Comment by pwalczysko** [comment]
I authorize my contributions to the IDR notebooks to be relicensed as BSD-2.

**Comment by jburel** [comment]
Thanks all, I will start the  change

**Comment by jburel** [comment]
see https://github.com/IDR/idr-notebooks/pull/111
