### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by Running-z** [IDR/idr-notebooks#66]
Hello, I am getting the following error when I use your example "IDR_API_example_script.ipynb"
:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-26-5b2416798de0> in <module>()
     23     payload = {'id': batch}
     24     print("payload is:", payload)
---> 25     for iid, thumb in session.get(THUMBNAILS_URL, params=payload).json().iteritems():
     26         _thumbnails[long(iid)] = thumb
     27 print("-thumbnails is:", _thumbnails)

AttributeError: 'dict' object has no attribute 'iteritems'

```
Can you tell me why? My python version is 3.5

**Comment by manics** [comment]
@Running-z we only support Python 2.7 at the moment since the OMERO.api doesn't run with Python 3. However I think the `IDR_API_example_script.ipynb` notebook only makes web requests, so it could be made to work with both Python 2 and 3. Try changing `iteritems` to `items`?

**Comment by Running-z** [comment]
@manics 
You are right, thank you!
