### ISSUE TITLE
Tutorial module error

### ISSUE THREAD

**Issue by Running-z** [IDR/idr-notebooks#69]
I got a module error when I ran your tutorial "Figure_1_Sampling_of_Phenotypes.ipynb":

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-65db7b40ea14> in <module>()
      1 
----> 2 import omero
      3 from idr import connection
      4 
      5 import numpy as np

ModuleNotFoundError: No module named 'omero'

```
And I can't install via pip:

```
(deep2.0.0) zh@zh:~$ pip install omero
Collecting omero
  Could not find a version that satisfies the requirement omero (from versions: )
No matching distribution found for omero

```
Can you tell me what is going on?

**Comment by manics** [comment]
I'm afraid OMERO isn't yet available on PyPi. The easiest way to get started is to use our online Virtual Analysis Environment: https://idr-analysis.openmicroscopy.org/ The "Public access" option doesn't require a login, it's available to anyone and will give you a temporary session where you can explore the notebooks in a preconfigured environment.

If you want to develop locally [Anaconda is the easiest way to get things setup](https://conda.io/docs/user-guide/tasks/manage-environments.html). You can use this environment file: https://github.com/IDR/idr-notebooks/blob/IDR-0.5.0/docker/environment-python2-idr.yml
