### ISSUE TITLE
Upgrade to Python3 code?

### ISSUE THREAD

**Issue by jhermann** [IDR/idr-notebooks#91]
At least "IDR API example script" contains some Python2-only code that is easily changed to Python3.

**Comment by manics** [comment]
We're limited by the OMERO python bindings which aren't compatible with Python 3. There's some ongoing investigation: https://trello.com/c/ZE3Cv4uv/111-request-convert-python-api-to-python3

**Comment by jhermann** [comment]
You have about 9 months left. ☺

The things I found, e.g. iteritems/long, could probably made py2+3 without a major runtime impact, and improve preparedness.

**Comment by jburel** [comment]
Everything has been updated to Py3
